import SVS13py.mf as mf
dic_bb_opt = {}

alpha_lowv = 1

#dic_bb_opt['big_cavity'] = {
#                                    'c':'k',
#                                    'sty':'.',
#                                    'fsty':None,
#                                    'regr':None,
#                                    'sty_regr':'k--',
#                                    'linestyle':'-',
#                                    'pos_text':None,
#                                    'plot_centers':True,
#                                    'markersize_centers':10,
#                                    'markeredgewidth_centers':0.5,
#                                    'markerfacecolor_centers':None,
#                                    'markeredgecolor_centers':'k',
#                                    'alpha':alpha_lowv,
#                                    'plot_ellipses':'aper',
#                                    'c_ell':'g',
#                                    'step_chan':1,
#                                    'label':'Rings I',
#                                    'centers_zorder':5,
#                                    'regr_zorder':4,
#                                    'ellipse_zorder':2}

dic_bb_opt['minor_bubble'] = {
                                    'c':'k',
                                    'sty':'.',
                                    'fsty':None,
                                    'regr':None,
                                    'sty_regr':'k--',
                                    'linestyle':'-',
                                    'pos_text':None,
                                    'plot_centers':True,
                                    'markersize_centers':10,
                                    'markeredgewidth_centers':0.5,
                                    'markerfacecolor_centers':None,
                                    'markeredgecolor_centers':'k',
                                    'alpha':alpha_lowv,
                                    'plot_ellipses':'aper',
                                    'c_ell':'g',
                                    'step_chan':1,
                                    'label':'Rings I',
                                    'centers_zorder':5,
                                    'regr_zorder':4,
                                    'ellipse_zorder':2}

dic_bb_opt['veryfirst_little_bubble'] = {
                                    'c':'k',
                                    'sty':'.',
                                    'fsty':None,
                                    'regr':3,
                                    'sty_regr':'k--',
                                    'linestyle':'-',
                                    'pos_text':None,
                                    'plot_centers':True,
                                    'markersize_centers':10,
                                    'markeredgewidth_centers':0.5,
                                    'markerfacecolor_centers':None,
                                    'markeredgecolor_centers':'k',
                                    'alpha':alpha_lowv,
                                    'plot_ellipses':'aper',
                                    'c_ell':'g',
                                    'step_chan':1,
                                    'label':None,
                                    'centers_zorder':5,
                                    'regr_zorder':4,
                                    'ellipse_zorder':1}

dic_bb_opt['veryfirst_bigger_bubble'] = {
                                    'c':'k',
                                    'sty':'.',
                                    'fsty':None,
                                    'linestyle':'-',
                                    'regr':3,
                                    'sty_regr':'k--',
                                    'pos_text':None,
                                    'plot_centers':True,
                                    'markersize_centers':10,
                                    'markeredgewidth_centers':0.5,
                                    'markerfacecolor_centers':None,
                                    'markeredgecolor_centers':'k',
                                    'alpha':alpha_lowv,
                                    'plot_ellipses':'aper',
                                    'c_ell':'g',
                                    'step_chan':1,
                                    'label':None,
                                    'centers_zorder':5,
                                    'regr_zorder':4,
                                    'ellipse_zorder':1}

dic_bb_opt['first_cavity'] = {
                          'c':'g',
                          'sty':'.',
                          'fsty':None,
                          'regr':1,
                          'sty_regr':'k--',
                          'linestyle':'-',
                          'pos_text':None,
                          'plot_centers':True,
                          'markersize_centers':10,
                          'markeredgewidth_centers':0.5,
                          'markerfacecolor_centers':None,
                          'markeredgecolor_centers':'k',
                          'alpha':alpha_lowv,
                          'plot_ellipses':'patches',
                          'theta1_pa':120,
                          'theta2_pa':40,
                          'c_ell':'b',
                          'step_chan':1,
                          'label':'Rings II',
                          'centers_zorder':5,
                          'regr_zorder':4,
                          'ellipse_zorder':None}

dic_bb_opt['first_cavity2'] = {
                          'c':'g',
                          'sty':'.',
                          'fsty':None,
                          'regr':None,
                          'sty_regr':'k--',
                          'linestyle':'-',
                          'pos_text':None,
                          'plot_centers':True,
                          'markersize_centers':10,
                          'markeredgewidth_centers':0.5,
                          'markerfacecolor_centers':None,
                          'markeredgecolor_centers':'k',
                          'alpha':0.1,
                          'plot_ellipses':'aper',
                          'c_ell':'b',
                          'step_chan':1,
                          'label':None,
                          'centers_zorder':5,
                          'regr_zorder':4,
                          'ellipse_zorder':None}

dic_bb_opt['first_cavity_tip'] = {
                          'c':'g',
                          'sty':'x',
                          'fsty':'none',
                          'regr':1,
                          'sty_regr':'k--',
                          'linestyle':'--',
                          'pos_text':None,
                          'plot_centers':True,
                          'markersize_centers':6,
                          'markeredgewidth_centers':0.5,
                          'markerfacecolor_centers':None,
                          'markeredgecolor_centers':'k',
                          'alpha':alpha_lowv,
                          'theta1_pa':120,
                          'theta2_pa':40,
                          'plot_ellipses':'patches',
                          'c_ell':'b',
                          'step_chan':1,
                          'label':None,
                          'centers_zorder':4,
                          'regr_zorder':3,
                          'ellipse_zorder':1}

dic_bb_opt['first_cavity_tip2'] = {
                          'c':'g',
                          'sty':'x',
                          'fsty':'none',
                          'regr':None,
                          'sty_regr':'k--',
                          'linestyle':'--',
                          'pos_text':None,
                          'plot_centers':True,
                          'markersize_centers':6,
                          'markeredgewidth_centers':0.5,
                          'markerfacecolor_centers':None,
                          'markeredgecolor_centers':'k',
                          'alpha':0.05,
                          'plot_ellipses':'filled_ellipse',
                          'c_ell':'b',
                          'step_chan':1,
                          'label':None,
                          'centers_zorder':4,
                          'regr_zorder':3,
                          'ellipse_zorder':1}


dic_bb_opt['second_cavity'] = {
                                    'c':'r',
                                    'sty':'.',
                                    'fsty':None,
                                    'regr':2,
                                    'sty_regr':'k--',
                                    'linestyle':'-',
                                    'pos_text':None,
                                    'plot_centers':True,
                                    'markersize_centers':10,
                                    'markeredgewidth_centers':0.5,
                                    'markerfacecolor_centers':None,
                                    'markeredgecolor_centers':'k',
                                    'alpha':alpha_lowv,
                                    'plot_ellipses':'patches',
                                    'theta1_pa':120,
                                    'theta2_pa':-30,
                                    'c_ell':'g',
                                    'step_chan':1,
                                    'label':'Rings III',
                                    'centers_zorder':5,
                                    'regr_zorder':4,
                                    'ellipse_zorder':None}

dic_bb_opt['second_cavity2'] = {
                                    'c':'r',
                                    'sty':'.',
                                    'fsty':None,
                                    'regr':None,
                                    'sty_regr':'k--',
                                    'linestyle':'-',
                                    'pos_text':None,
                                    'plot_centers':True,
                                    'markersize_centers':10,
                                    'markeredgewidth_centers':0.5,
                                    'markerfacecolor_centers':None,
                                    'markeredgecolor_centers':'k',
                                    'alpha':0.1,
                                    'plot_ellipses':'aper',
                                    'c_ell':'g',
                                    'step_chan':1,
                                    'label':None,
                                    'centers_zorder':5,
                                    'regr_zorder':4,
                                    'ellipse_zorder':None}


dic_bb_opt['second_cavity_tip'] = {
                          'c':'r',
                          'sty':'x',
                          'fsty':'none',
                          'regr':None,
                          'sty_regr':'k--',
                          'linestyle':'--',
                          'pos_text':None,
                          'plot_centers':True,
                          'markersize_centers':6,
                          'markeredgewidth_centers':0.5,
                          'markerfacecolor_centers':None,
                          'markeredgecolor_centers':'k',
                          'alpha':alpha_lowv,
                          'theta1_pa':120,
                          'theta2_pa':40,
                          'plot_ellipses':'patches',
                          'c_ell':'b',
                          'step_chan':1,
                          'label':None,
                          'centers_zorder':4,
                          'regr_zorder':3,
                          'ellipse_zorder':2}


dic_bb_opt['second_cavity_tip2'] = {
                          'c':'r',
                          'sty':'x',
                          'fsty':'none',
                          'regr':None,
                          'sty_regr':'k--',
                          'linestyle':'-',
                          'pos_text':None,
                          'plot_centers':True,
                          'markersize_centers':6,
                          'markeredgewidth_centers':0.5,
                          'markerfacecolor_centers':None,
                          'markeredgecolor_centers':'k',
                          'alpha':0.05,
                          'plot_ellipses':'filled_ellipse',
                          'c_ell':'b',
                          'step_chan':1,
                          'label':None,
                          'centers_zorder':4,
                          'regr_zorder':3,
                          'ellipse_zorder':2}



dic_bb_opt['first_knot_rings'] = {
                          'c':'gray',
                          'sty':'.',
                          'fsty':'none',
                          'regr':None,
                          'sty_regr':'k--',
                          'linestyle':'-',
                          'pos_text':None,
                          'plot_centers':True,
                          'markersize_centers':10,
                          'markeredgewidth_centers':0.5,
                          'markerfacecolor_centers':None,
                          'markeredgecolor_centers':'k',
                          'alpha':alpha_lowv,
                          'theta1_pa':130,
                          'theta2_pa':-5,
                          'plot_ellipses':'patches',
                          'c_ell':'b',
                          'step_chan':1,
                          'label':'Rings IV',
                          'centers_zorder':4,
                          'regr_zorder':3,
                          'ellipse_zorder':2}


dic_bb_opt['first_knot_rings2'] = {
                          'c':'gray',
                          'sty':'.',
                          'fsty':'none',
                          'regr':None,
                          'sty_regr':'k--',
                          'linestyle':'-',
                          'pos_text':None,
                          'plot_centers':True,
                          'markersize_centers':10,
                          'markeredgewidth_centers':0.5,
                          'markerfacecolor_centers':None,
                          'markeredgecolor_centers':'k',
                          'alpha':0.1,
                          'plot_ellipses':'aper',
                          'c_ell':'b',
                          'step_chan':1,
                          'label':None,
                          'centers_zorder':4,
                          'regr_zorder':3,
                          'ellipse_zorder':2}

dic_bb_opt['first_knot'] = {
                          'c':'gray',
                          'sty':'x',
                          'fsty':'none',
                          'regr':None,
                          'sty_regr':'k--',
                          'linestyle':'--',
                          'pos_text':None,
                          'plot_centers':True,
                          'markersize_centers':6,
                          'markeredgewidth_centers':0.5,
                          'markerfacecolor_centers':None,
                          'markeredgecolor_centers':'k',
                          'alpha':alpha_lowv,
                          'theta1_pa':130,
                          'theta2_pa':-5,
                          'plot_ellipses':'patches',
                          'c_ell':'b',
                          'step_chan':1,
                          'label':None,
                          'centers_zorder':3,
                          'regr_zorder':3,
                          'ellipse_zorder':2}


dic_bb_opt['first_knot2'] = {
                          'c':'gray',
                          'sty':'x',
                          'fsty':'none',
                          'regr':None,
                          'sty_regr':'k--',
                          'linestyle':'-',
                          'pos_text':None,
                          'plot_centers':True,
                          'markersize_centers':6,
                          'markeredgewidth_centers':0.5,
                          'markerfacecolor_centers':None,
                          'markeredgecolor_centers':'k',
                          'alpha':0.05,
                          'plot_ellipses':'filled_ellipse',
                          'c_ell':'b',
                          'step_chan':1,
                          'label':None,
                          'centers_zorder':3,
                          'regr_zorder':3,
                          'ellipse_zorder':2}

dic_bb_opt['second_knot_rings_dubious'] = {
                          'c':'m',
                          'sty':'.',
                          'fsty':'none',
                          'regr':None,
                          'sty_regr':'k--',
                          'linestyle':'-',
                          'pos_text':None,
                          'plot_centers':True,
                          'markersize_centers':10,
                          'markeredgewidth_centers':0.5,
                          'markerfacecolor_centers':None,
                          'markeredgecolor_centers':'k',
                          'alpha':alpha_lowv,
                          'theta1_pa':130,
                          'theta2_pa':-5,
                          'plot_ellipses':'patches',
                          'c_ell':'b',
                          'step_chan':1,
                          'label':'Rings V',
                          'centers_zorder':4,
                          'regr_zorder':3,
                          'ellipse_zorder':2}


dic_bb_opt['second_knot_rings_dubious2'] = {
                          'c':'m',
                          'sty':'.',
                          'fsty':'none',
                          'regr':None,
                          'sty_regr':'k--',
                          'linestyle':'-',
                          'pos_text':None,
                          'plot_centers':True,
                          'markersize_centers':10,
                          'markeredgewidth_centers':0.5,
                          'markerfacecolor_centers':None,
                          'markeredgecolor_centers':'k',
                          'alpha':0.1,
                          'plot_ellipses':'aper',
                          'c_ell':'b',
                          'step_chan':1,
                          'label':None,
                          'centers_zorder':4,
                          'regr_zorder':3,
                          'ellipse_zorder':2}

#dic_bb_opt['low_res_arcs_dubious'] = {
#                                    'c':'g', 'sty':'.', 'fsty':None,
#                                    'regr':None, 'sty_regr':'k--',
#                                    'linestyle':'-',
#                                    'pos_text':None,
#                                    'plot_centers':True,
#                                     'markersize_centers':10,
#                                     'markeredgewidth_centers':0.5,
#                                     'markerfacecolor_centers':None,
#                                     'markeredgecolor_centers':'k',
#                                    'alpha':alpha_lowv,
#                                    'plot_ellipses':'patches',
#                                    'theta1_pa':120,
#                                    'theta2_pa':-30,
#                                    'c_ell':'g',
#                                    'step_chan':1,
#                                    'label':True,
#                                    'centers_zorder':1,
#                                    'regr_zorder':1,
#                                    'ellipse_zorder':3}
#
#dic_bb_opt['low_res_arcs_dubious2'] = {
#                                    'c':'g', 'sty':'.', 'fsty':None,
#                                    'regr':None, 'sty_regr':'k--',
#                                    'linestyle':'-',
#                                    'pos_text':None,
#                                    'plot_centers':True,
#                                    'markersizhttps://youtu.be/IBhvat5u9wIe_centers':10,
#                                    'markeredgewidth_centers':0.5,
#                                    'markerfacecolor_centers':None,
#                                    'markeredgecolor_centers':'k',
#                                    'alpha':0.05,
#                                    'plot_ellipses':'aper',
#                                    'c_ell':'g',
#                                    'step_chan':1,
#                                    'label':True,
#                                    'centers_zorder':1,
#                                    'regr_zorder':1,
#                                    'ellipse_zorder':3}

dic_bb_opt['low_res_arcs'] = {
                                    'c':'b', 'sty':'.', 'fsty':None,
                                    'regr':None, 'sty_regr':'k--',
                                    'linestyle':'-',
                                    'pos_text':None,
                                    'plot_centers':True,
                                    'markersize_centers':10,
                                    'markeredgewidth_centers':0.5,
                                    'markerfacecolor_centers':None,
                                    'markeredgecolor_centers':'k',
                                    'alpha':alpha_lowv,
                                    'plot_ellipses':'patches',
                                    'theta1_pa':120,
                                    'theta2_pa':-30,
                                    'c_ell':'g',
                                    'step_chan':1,
                                    'label':'Rings VI',
                                    'centers_zorder':5,
                                    'regr_zorder':4,
                                    'ellipse_zorder':4}

dic_bb_opt['low_res_arcs2'] = {
                                    'c':'b',
                                    'sty':'.',
                                    'fsty':None,
                                    'regr':None,
                                    'sty_regr':'k--',
                                    'linestyle':'-',
                                    'pos_text':None,
                                    'plot_centers':True,
                                    'markersize_centers':10,
                                    'markeredgewidth_centers':0.5,
                                    'markerfacecolor_centers':None,
                                    'markeredgecolor_centers':'k',
                                    'alpha':0.1,
                                    'plot_ellipses':'aper',
                                    'c_ell':'g',
                                    'step_chan':1,
                                    'label':None,
                                    'centers_zorder':5,
                                    'regr_zorder':4,
                                    'ellipse_zorder':4}



dic_bb_opt['low_res_arcs_tip'] = {
                                    'c':'b',
                                    'sty':'x',
                                    'fsty':'none',
                                    'regr':None,
                                    'sty_regr':'k--',
                                    'linestyle':'--',
                                    'pos_text':None,
                                    'plot_centers':True,
                                    'markersize_centers':6,
                                    'markeredgewidth_centers':0.5,
                                    'markerfacecolor_centers':None,
                                    'markeredgecolor_centers':'k',
                                    'alpha':alpha_lowv,
                                    'plot_ellipses':'patches',
                                    'theta1_pa':120,
                                    'theta2_pa':-30,
                                    'c_ell':'k',
                                    'step_chan':1,
                                    'label':None,
                                    'centers_zorder':4,
                                    'regr_zorder':4,
                                    'ellipse_zorder':4}

dic_bb_opt['low_res_arcs_tip2'] = {
                                    'c':'b',
                                    'sty':'x',
                                    'fsty':'none',
                                    'regr':None,
                                    'sty_regr':'k--',
                                    'linestyle':'--',
                                    'pos_text':None,
                                    'plot_centers':True,
                                    'markersize_centers':6,
                                    'markeredgewidth_centers':0.5,
                                    'markerfacecolor_centers':None,
                                    'markeredgecolor_centers':'k',
                                    'alpha':0.05,
                                    'plot_ellipses':'filled_ellipse',
                                    'c_ell':'g',
                                    'step_chan':1,
                                    'label':None,
                                    'centers_zorder':4,
                                    'regr_zorder':4,
                                    'ellipse_zorder':4}



#dic_bb_opt['little_tip'] = {
#                                    'c':'c',
#                                    'sty':'.',
#                                    'fsty':None,
#                                    'regr':None,
#                                    'sty_regr':'k--',
#                                    'linestyle':'--',
#                                    'pos_text':[mf.default_params['vla4b_deg'][0]+0.00004, mf.default_params['vla4b_deg'][1]+0.00005],
#                                    'plot_centers':True,
#                                    'markersize_centers':10,
#                                    'markeredgewidth_centers':0.5,
#                                    'markerfacecolor_centers':'None',
#                                    'markeredgecolor_centers':None,
#                                    'alpha':0.5,
#                                    'plot_ellipses':'patches',
#                                    'theta1_pa':120,
#                                    'theta2_pa':-30,
#                                    'c_ell':'g',
#                                    'step_chan':1,
#                                    'label':None,
#                                    'centers_zorder':5,
#                                    'regr_zorder':4,
#                                    'ellipse_zorder':4}
#
#
#bbs_zoom = ['main_arcs_1bb',
#            'main_arcs_1bb2',
#            'first_cavity_tip',
#            'first_cavity_tip2',
#            'second_cavity_tip',
#            'second_cavity_tip2',
#            'secondary_arcs_annulus',
#            'secondary_arcs_annulus2',
#            'minor_bubble',
#            'veryfirst_little_bubble',
#            'veryfirst_bigger_bubble',]

dic_bb_zoom_opt = {}

#dic_bb_zoom_opt['big_cavity'] = {
#                                    'c':'k',
#                                    'sty':'.',
#                                    'fsty':None,
#                                    'regr':None,
#                                    'sty_regr':'k--',
#                                    'linestyle':'-',
#                                    'pos_text':[mf.default_params['vla4a_deg'][0]-0.00004,mf.default_params['vla4a_deg'][1]+0.00003],
#                                    'plot_centers':True,
#                                    'markersize_centers':10,
#                                    'markeredgewidth_centers':0.5,
#                                    'markerfacecolor_centers':None,
#                                    'markeredgecolor_centers':'k',
#                                    'alpha':alpha_lowv,
#                                    'plot_ellipses':'aper',
#                                    'c_ell':'g',
#                                    'step_chan':1,
#                                    'label':True,
#                                    'centers_zorder':5,
#                                    'regr_zorder':4,
#                                    'ellipse_zorder':2}

dic_bb_zoom_opt['minor_bubble'] = {
                                    'c':'k',
                                    'sty':'.',
                                    'fsty':None,
                                    'regr':3, 'sty_regr':'k--',
                                    'linestyle':'-',
                                    'pos_text':[mf.default_params['vla4a_deg'][0]-0.00004,
                                                mf.default_params['vla4a_deg'][1]+0.00003],
                                    'plot_centers':True,
                                    'markersize_centers':10,
                                    'markeredgewidth_centers':0.5,
                                    'markerfacecolor_centers':None,
                                    'markeredgecolor_centers':'k',
                                    'alpha':alpha_lowv,
                                    'plot_ellipses':'aper',
                                    'c_ell':'g',
                                    'step_chan':1,
                                    'label':True,
                                    'centers_zorder':5,
                                    'regr_zorder':4,
                                    'ellipse_zorder':2}

dic_bb_zoom_opt['veryfirst_little_bubble'] = {
                                    'c':'k',
                                    'sty':'.',
                                    'fsty':None,
                                    'regr':3,
                                    'sty_regr':'k--',
                                    'linestyle':'-',
                                    'pos_text':None,
                                    'plot_centers':True,
                                    'markersize_centers':10,
                                    'markeredgewidth_centers':0.5,
                                    'markerfacecolor_centers':None,
                                    'markeredgecolor_centers':'k',
                                    'alpha':alpha_lowv,
                                    'plot_ellipses':'aper',
                                    'c_ell':'g',
                                    'step_chan':1,
                                    'label':True,
                                    'centers_zorder':5,
                                    'regr_zorder':4,
                                    'ellipse_zorder':1}

dic_bb_zoom_opt['veryfirst_bigger_bubble'] = {
                                    'c':'k',
                                    'sty':'.',
                                    'fsty':None,
                                    'linestyle':'-',
                                    'regr':3,
                                    'sty_regr':'k--',
                                    'pos_text':None,
                                    'plot_centers':True,
                                    'markersize_centers':10,
                                    'markeredgewidth_centers':0.5,
                                    'markerfacecolor_centers':None,
                                    'markeredgecolor_centers':'k',
                                    'alpha':alpha_lowv,
                                    'plot_ellipses':'aper',
                                    'c_ell':'g',
                                    'step_chan':1,
                                    'label':True,
                                    'centers_zorder':5,
                                    'regr_zorder':4,
                                    'ellipse_zorder':1}

dic_bb_zoom_opt['first_cavity'] = {
                          'c':'g',
                          'sty':'.',
                          'fsty':None,
                          'regr':1,
                          'sty_regr':'k--',
                          'linestyle':'-',
                          'pos_text':[mf.default_params['vla4a_deg'][0],
                                      mf.default_params['vla4a_deg'][1]+0.00006],
                          'plot_centers':True,
                          'markersize_centers':10,
                          'markeredgewidth_centers':0.5,
                          'markerfacecolor_centers':None,
                          'markeredgecolor_centers':'k',
                          'alpha':alpha_lowv,
                          'plot_ellipses':'patches',
                          'theta1_pa':120,
                          'theta2_pa':40,
                          'c_ell':'b',
                          'step_chan':1,
                          'label':True,
                          'centers_zorder':5,
                          'regr_zorder':4,
                          'ellipse_zorder':1}

dic_bb_zoom_opt['first_cavity2'] = {
                          'c':'g',
                          'sty':'.',
                          'fsty':None,
                          'regr':1,
                          'sty_regr':'k--',
                          'linestyle':'-',
                          'pos_text':None,
                          'plot_centers':True,
                          'markersize_centers':10,
                          'markeredgewidth_centers':0.5,
                          'markerfacecolor_centers':None,
                          'markeredgecolor_centers':'k',
                          'alpha':0.1,
                          'plot_ellipses':'aper',
                          'c_ell':'b',
                          'step_chan':1,
                          'label':True,
                          'centers_zorder':5,
                          'regr_zorder':4,
                          'ellipse_zorder':2}

dic_bb_zoom_opt['first_cavity_tip'] = {
                          'c':'g',
                          'sty':'x',
                          'fsty':'none',
                          'regr':1,
                          'sty_regr':'k--',
                          'linestyle':'--',
                          'pos_text':None,
                          'plot_centers':True,
                          'markersize_centers':6,
                          'markeredgewidth_centers':0.5,
                          'markerfacecolor_centers':None,
                          'markeredgecolor_centers':'k',
                          'alpha':0.5,
                          'theta1_pa':120,
                          'theta2_pa':40,
                          'plot_ellipses':'patches',
                          'c_ell':'b',
                          'step_chan':1,
                          'label':True,
                          'centers_zorder':4,
                          'regr_zorder':0,
                          'ellipse_zorder':0}

dic_bb_zoom_opt['first_cavity_tip2'] = {
                          'c':'g',
                          'sty':'x',
                          'fsty':'none',
                          'regr':None,
                          'sty_regr':'k--',
                          'linestyle':'--',
                          'pos_text':None,
                          'plot_centers':True,
                          'markersize_centers':6,
                          'markeredgewidth_centers':0.5,
                          'markerfacecolor_centers':None,
                          'markeredgecolor_centers':'k',
                          'alpha':0.1,
                          'plot_ellipses':'filled_ellipse',
                          'c_ell':'b',
                          'step_chan':1,
                          'label':True,
                          'centers_zorder':4,
                          'regr_zorder':0,
                          'ellipse_zorder':1}


dic_bb_zoom_opt['second_cavity'] = {
                                    'c':'r',
                                    'sty':'.',
                                    'fsty':None,
                                    'regr':2,
                                    'sty_regr':'k--',
                                    'linestyle':'-',
                                    'pos_text':[mf.default_params['vla4b_deg'][0]+0.00004,
                                                mf.default_params['vla4b_deg'][1]+0.00005],
                                    'plot_centers':True,
                                    'markersize_centers':10,
                                    'markeredgewidth_centers':0.5,
                                    'markerfacecolor_centers':None,
                                    'markeredgecolor_centers':'k',
                                    'alpha':alpha_lowv,
                                    'plot_ellipses':'patches',
                                    'theta1_pa':120,
                                    'theta2_pa':-30,
                                    'c_ell':'g',
                                    'step_chan':1,
                                    'label':True,
                                    'centers_zorder':5,
                                    'regr_zorder':4,
                                    'ellipse_zorder':2}

dic_bb_zoom_opt['second_cavity2'] = {
                                    'c':'r',
                                    'sty':'.',
                                    'fsty':None,
                                    'regr':None,
                                    'sty_regr':'k--',
                                    'linestyle':'-',
                                    'pos_text':None,
                                    'plot_centers':True,
                                    'markersize_centers':10,
                                    'markeredgewidth_centers':0.5,
                                    'markerfacecolor_centers':None,
                                    'markeredgecolor_centers':'k',
                                    'alpha':0.1,
                                    'plot_ellipses':'aper',
                                    'c_ell':'g',
                                    'step_chan':1,
                                    'label':True,
                                    'centers_zorder':5,
                                    'regr_zorder':4,
                                    'ellipse_zorder':2}


dic_bb_zoom_opt['second_cavity_tip'] = {
                          'c':'r',
                          'sty':'x',
                          'fsty':'none',
                          'regr':None,
                          'sty_regr':'k--',
                          'linestyle':'--',
                          'pos_text':None,
                          'plot_centers':True,
                          'markersize_centers':6,
                          'markeredgewidth_centers':0.5,
                          'markerfacecolor_centers':None,
                          'markeredgecolor_centers':'k',
                          'alpha':alpha_lowv,
                          'theta1_pa':120,
                          'theta2_pa':40,
                          'plot_ellipses':'patches',
                          'c_ell':'b',
                          'step_chan':1,
                          'label':None,
                          'centers_zorder':4,
                          'regr_zorder':3,
                          'ellipse_zorder':3}


dic_bb_zoom_opt['second_cavity_tip2'] = {
                          'c':'r',
                          'sty':'x',
                          'fsty':'none',
                          'regr':None,
                          'sty_regr':'k--',
                          'linestyle':'-',
                          'pos_text':None,
                          'plot_centers':True,
                          'markersize_centers':6,
                          'markeredgewidth_centers':0.5,
                          'markerfacecolor_centers':None,
                          'markeredgecolor_centers':'k',
                          'alpha':0.05,
                          'plot_ellipses':'filled_ellipse',
                          'c_ell':'b',
                          'step_chan':1,
                          'label':None,
                          'centers_zorder':4,
                          'regr_zorder':3,
                          'ellipse_zorder':3}


